// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tbuztoydhntbewcllzdn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRidXp0b3lkaG50YmV3Y2xsemRuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NDQwMDcsImV4cCI6MjA2NTUyMDAwN30.bDj7k5n1uvVnELzbOfngmg6FHGi-17XmxvmmI_CSMt4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);